### ISSUE TITLE
The 3D display won't show

### ISSUE THREAD

**Issue by danieljfferguson** [piiq/helyx-os-for-mac#1]
On the right, my window where the 3D display should show is blank.

In the terminal it says:
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

Which I suspect is a reason why it isn't showing. Any help would be appreciated - this is for my masters thesis!

![Screenshot 2020-05-13 at 13 08 02](https://user-images.githubusercontent.com/64608450/81810416-d0068d00-951a-11ea-9e24-5b458b24beb9.png)

**Comment by piiq** [comment]
Hey! Sorry for taking long to spot this issue. If this problem is still on your desk - let me know, I will try to debug this issue with you.

**Comment by piiq** [comment]
Hey @danieljfferguson 
Thanks for pointing out this issue. The X11 setup was missing from the manual. I've updated the readme to mention this.

On your host machine (the mac) execute the following in the terminal

```
defaults write org.macosforge.xquartz.X11 enable_iglx -bool true
```

This should enable using the mac for 3d viewing over X11
