### ISSUE TITLE
The 3D viewing is still not valid 

### ISSUE THREAD

**Issue by gangw0632** [piiq/helyx-os-for-mac#2]
Hi!

I'm running the MacOS Bigsur 11.6 with the XQuartz 2.8.1 (the latest RC), following the set-up released in README (I entered the "defaults write org.macosforge.xquartz.X11 enable_iglx -bool true"). But the same error appears and the display of 3D cannot be shown. Could you please have a look? 

"libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast"

Best regards,
Gang

![image](https://user-images.githubusercontent.com/55394229/137424425-d8cd682e-dde8-4891-b9dd-ba83fbf5ec09.png)

**Comment by piiq** [comment]
Hi @gangw0632 👋
Are you on an M1 mac?

**Comment by gangw0632** [comment]
Hi @piiq I'm on a intel-chip Macbook.

**Comment by piiq** [comment]
@gangw0632 Ok, let me check this on my end

**Comment by gangw0632** [comment]
Emmm,,I think I worked out through the upgrading my X11 Xquartz to 2.8.1, the latest one. Previously mine is 2.7....So I think it would be better if your could elaborate README by adding the recommendation of Xquartz's version is 2.8.1. thanks!

**Comment by piiq** [comment]
Great!
Were you doing a fresh launch or was the container built some time ago?

**Comment by gangw0632** [comment]
I’m doing a fresh launch, and the container was built just half an hour ago, since I restore all the contents in my Mac. So, everything is good until now. Wish a nice weekend!

Best regards,
Gang

**Comment by piiq** [comment]
Thanks 👋
I'll update the readme following this thread and close the issue
