### ISSUE TITLE
Is this possible to run on a M1-Pro Mac?

### ISSUE THREAD

**Issue by gangw0632** [piiq/helyx-os-for-mac#3]
Is this possible to run on a M1-Pro Mac? I've tried to install but I fail..The HELYX-OS is a x86-based software, right?

**Comment by piiq** [comment]
I haven't yet tried this myself, but if I understand correctly, if the X11 screen forwarding from the container to the host works on M1 macs - it should work.
If it doesn't work natively, I would try to run it with Rosetta

Let me know if you succeed, or encounter errors along the way

**Comment by gangw0632** [comment]
I think the X11 is feasible to run on ARM-based Mac, but the HELYX cannot be run using your default release..So, could you please have a test and then implement that with Rosetta 2? 

Thanks!

**Comment by piiq** [comment]
I will get my hands on an m1 machine in a couple of weeks. I will let you know how it goes

**Comment by ahitaa** [comment]
I've tried to build the container but failed:
`------
executor failed running [/bin/sh -c set -x && 	apt-get -y update && 	apt-get -y upgrade && 	apt-get -y install software-properties-common && 	apt-get -y install locales && 	apt-get -y install apt-transport-https && 	apt-get -y install wget bzip2 zip && 	add-apt-repository ppa:openjdk-r/ppa  && 	apt-get -y update && 	apt-get -y install vtk6 libvtk6-java openjdk-7-jre openjdk-7-jdk libglu1-mesa libgl1-mesa-glx && 	add-apt-repository http://dl.openfoam.org/ubuntu && 	sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -" && 	apt-get update && 	apt-get -y install openfoam4]: exit code: 100
ERROR: Service 'cfd_apps' failed to build : Build failed
./app-run.sh: line 2: xhost: command not found`

**Comment by piiq** [comment]
Hi, a small update here.

I did try building the whole thing on an m1 mac and there are 2 problems.
1. The `openjdk-7-jdk` that was used by the container as a requirement to run HelyxOS is old and deprecated and missing
2. If the docker engine is run natively (not rosetta) - during the build `apt` tries to get an `arm64` package of openfoam that's absent (as expected).

I'll have a look if I can inherit from the openfoam container and make the gui work from there

I'll post an update

**Comment by gangw0632** [comment]
> 

Thank you very much!

**Comment by gangw0632** [comment]
Hi! have you made some progress on that? :)

**Comment by piiq** [comment]
Hey, thanks for the poke

Looked into it. I can run in now, but there's no visualization available
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/11668535/178610489-24314a3b-e4fa-4de9-8205-3b535ea81d26.png">

I've pushed my changes into this PR https://github.com/piiq/helyx-os-for-mac/pull/4
I don't know if it's x11 related or java/vtk related yet. There are 2 errors that are a good entrypoint for searching

Feel free to use the code in the PR branch to experiment and please share your findings if you bump into some hints how to bring the 3D viewport back

**Comment by gangw0632** [comment]
Hi! 

I find it running normally as expected, such as the visualization of the geometry and the mesh below. Thanks for your great work!

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/55394229/178919323-546b867f-1459-4e9f-9d9a-4a8f1173faed.png">

**Comment by piiq** [comment]
Oh great! I'll merge the updates once i clean up
